Disable camera scenes setting
Aelto/W3_RandomEncounters_Tweaks pull request #42
Opened 2020-11-18 23:33 UTC by SpontanCombust

- added menu option to disable camera scenes on key events
- moved camera playing specifically to seperate functions for cutscenes
- added disable camera scenes entry to strings

2020-11-18 23:46 UTC, SpontanCombust commented on src/settings.ws
> +  // Spontan edit
you can delete that

2020-11-19 11:35 UTC, Aelto commented on mod-menu.xml
> +                <Entry varId="RERcameraCutscenesDisabled"		value="0"	/>
@SpontanCombust i think there is a mistake here, below the varId is `RERcameraScenesDisabled` when here it's `RERcameraCutscenesDisabled`. It means the preset won't work.

2020-11-19 11:46 UTC, Aelto commented on mod-menu.xml
> +                <Entry varId="RERcameraCutscenesDisabled"		value="0"	/>
Make sure it's the same ID you use in the settings too 👍

2020-11-19 11:51 UTC, SpontanCombust commented on mod-menu.xml
> +                <Entry varId="RERcameraCutscenesDisabled"		value="0"	/>
Yeah, you're right. I forgot to change it for the preset.

2020-11-19 12:48 UTC, Aelto requested changes
There is a mistake with the preset in the mod menu i think. I made a comment about it

2020-11-19 12:50 UTC, Aelto approved these changes

2020-11-19 12:51 UTC, Aelto commented
Alright, the code is perfect i'm merging it. Thank you very much!

2020-11-19 12:52 UTC, merged